### ISSUE TITLE
Update icon: ProtonMail

### ISSUE THREAD

**Issue by rkhmlvch** [krisu5/aegis-icons#487] opened 2022-01-16 18:05 UTC
- URL of the site or app **(required):** https://protonmail.com
- Reason for update **(required):** ProtonMail updated the design and website colours, so the logo became darker and more contrast.
- Logo resources for the icon **(optional):** https://protonmail.com/media-kit

**Comment by krisu5** [comment] 2022-01-16 18:07
Duplicate of #329, the color is still in use: https://protonmail.com/media-kit

**Closed as completed by krisu5** 2022-01-16 18:07 UTC
Labels: Update, Rejected / Dropped, Duplicate

**Comment by rkhmlvch** [comment] 2022-01-16 18:09
![изображение](https://user-images.githubusercontent.com/8180837/149672224-a36c776e-382b-48e9-9449-366cab797325.png)
It looks like this and the bright variant is legacy: 
![изображение](https://user-images.githubusercontent.com/8180837/149672265-e6d05162-cacf-49c8-8ea0-5048c7fd4152.png)


> Duplicate of #329, the color is still in use: https://protonmail.com/media-kit

**Comment by krisu5** [comment] 2022-01-16 18:15
Only thing that matters here is media kit's logo section and this logo color is still in use based of that.

**Comment by rkhmlvch** [comment] 2022-01-16 18:22
Okay, I got it.
